
package asynk.se.client;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BuyerService", targetNamespace = "http://local:8085/Buyers")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BuyerService {


    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<se.client.GetBuyerListResponse>
     */
    @WebMethod(operationName = "getBuyerList")
    @RequestWrapper(localName = "getBuyerList", targetNamespace = "http://local:8085/Buyers", className = "se.client.GetBuyerList")
    @ResponseWrapper(localName = "getBuyerListResponse", targetNamespace = "http://local:8085/Buyers", className = "se.client.GetBuyerListResponse")
    public Response<GetBuyerListResponse> getBuyerListAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getBuyerList")
    @RequestWrapper(localName = "getBuyerList", targetNamespace = "http://local:8085/Buyers", className = "se.client.GetBuyerList")
    @ResponseWrapper(localName = "getBuyerListResponse", targetNamespace = "http://local:8085/Buyers", className = "se.client.GetBuyerListResponse")
    public Future<?> getBuyerListAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetBuyerListResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns se.client.Buyer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBuyerList", targetNamespace = "http://local:8085/Buyers", className = "se.client.GetBuyerList")
    @ResponseWrapper(localName = "getBuyerListResponse", targetNamespace = "http://local:8085/Buyers", className = "se.client.GetBuyerListResponse")
    @Action(input = "http://local:8085/Buyers/BuyerService/getBuyerListRequest", output = "http://local:8085/Buyers/BuyerService/getBuyerListResponse")
    public Buyer getBuyerList();

}
