
package asynk.se.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Buyers", targetNamespace = "http://local:8085/Buyers", wsdlLocation = "http://localhost:8082/Buyers?wsdl")
public class Buyers
    extends Service
{

    private final static URL BUYERS_WSDL_LOCATION;
    private final static WebServiceException BUYERS_EXCEPTION;
    private final static QName BUYERS_QNAME = new QName("http://local:8085/Buyers", "Buyers");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/Buyers?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUYERS_WSDL_LOCATION = url;
        BUYERS_EXCEPTION = e;
    }

    public Buyers() {
        super(__getWsdlLocation(), BUYERS_QNAME);
    }

    public Buyers(WebServiceFeature... features) {
        super(__getWsdlLocation(), BUYERS_QNAME, features);
    }

    public Buyers(URL wsdlLocation) {
        super(wsdlLocation, BUYERS_QNAME);
    }

    public Buyers(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BUYERS_QNAME, features);
    }

    public Buyers(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Buyers(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BuyerService
     */
    @WebEndpoint(name = "BuyersPort")
    public BuyerService getBuyersPort() {
        return super.getPort(new QName("http://local:8085/Buyers", "BuyersPort"), BuyerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BuyerService
     */
    @WebEndpoint(name = "BuyersPort")
    public BuyerService getBuyersPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://local:8085/Buyers", "BuyersPort"), BuyerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUYERS_EXCEPTION!= null) {
            throw BUYERS_EXCEPTION;
        }
        return BUYERS_WSDL_LOCATION;
    }

}
