
package sample.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TicketService", targetNamespace = "http://local")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TicketService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns sample.client.Ticket
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createStatement", targetNamespace = "http://local", className = "sample.client.CreateStatement")
    @ResponseWrapper(localName = "createStatementResponse", targetNamespace = "http://local", className = "sample.client.CreateStatementResponse")
    @Action(input = "http://local/TicketService/createStatementRequest", output = "http://local/TicketService/createStatementResponse")
    public Ticket createStatement(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Buyer> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Film arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns sample.client.Ticket
     */
    @WebMethod(operationName = "Pass")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Pass", targetNamespace = "http://local", className = "sample.client.Pass")
    @ResponseWrapper(localName = "PassResponse", targetNamespace = "http://local", className = "sample.client.PassResponse")
    @Action(input = "http://local/TicketService/PassRequest", output = "http://local/TicketService/PassResponse")
    public Ticket pass(
        @WebParam(name = "arg0", targetNamespace = "")
        Ticket arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Buyer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
