
package sample.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TicketExam", targetNamespace = "http://local", wsdlLocation = "http://127.0.0.1:8084/ExamSvcWeb/exampass?wsdl")
public class TicketExam
    extends Service
{

    private final static URL TICKETEXAM_WSDL_LOCATION;
    private final static WebServiceException TICKETEXAM_EXCEPTION;
    private final static QName TICKETEXAM_QNAME = new QName("http://local", "TicketExam");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8084/ExamSvcWeb/exampass?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TICKETEXAM_WSDL_LOCATION = url;
        TICKETEXAM_EXCEPTION = e;
    }

    public TicketExam() {
        super(__getWsdlLocation(), TICKETEXAM_QNAME);
    }

    public TicketExam(WebServiceFeature... features) {
        super(__getWsdlLocation(), TICKETEXAM_QNAME, features);
    }

    public TicketExam(URL wsdlLocation) {
        super(wsdlLocation, TICKETEXAM_QNAME);
    }

    public TicketExam(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TICKETEXAM_QNAME, features);
    }

    public TicketExam(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicketExam(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TicketService
     */
    @WebEndpoint(name = "TicketExamPort")
    public TicketService getTicketExamPort() {
        return super.getPort(new QName("http://local", "TicketExamPort"), TicketService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketService
     */
    @WebEndpoint(name = "TicketExamPort")
    public TicketService getTicketExamPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://local", "TicketExamPort"), TicketService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TICKETEXAM_EXCEPTION!= null) {
            throw TICKETEXAM_EXCEPTION;
        }
        return TICKETEXAM_WSDL_LOCATION;
    }

}
